// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ8t6TxhWYmJYWTwfYCwLqvX9ZuWxe4CU',
    appId: '1:699043853640:web:f1729358851d23b3ce6f7d',
    messagingSenderId: '699043853640',
    projectId: 'flarus-app',
    authDomain: 'flarus-app.firebaseapp.com',
    storageBucket: 'flarus-app.firebasestorage.app',
    measurementId: 'G-2GSZXBR7H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCViISlF2YfQKDcfJZnXLBtqYZShOiQerY',
    appId: '1:699043853640:android:6a79de72c896b1eace6f7d',
    messagingSenderId: '699043853640',
    projectId: 'flarus-app',
    storageBucket: 'flarus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp5Fuo-f3BdrhCpM60StDd15bzQuE4L7o',
    appId: '1:699043853640:ios:4e7c363ebbb0b2e9ce6f7d',
    messagingSenderId: '699043853640',
    projectId: 'flarus-app',
    authDomain: 'flarus-app.firebaseapp.com',
    storageBucket: 'flarus-app.firebasestorage.app',
    iosBundleId: 'com.flarus.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp5Fuo-f3BdrhCpM60StDd15bzQuE4L7o',
    appId: '1:699043853640:ios:6ee2dded2489e7d5ce6f7d',
    messagingSenderId: '699043853640',
    projectId: 'flarus-app',
    storageBucket: 'flarus-app.firebasestorage.app',
    iosBundleId: 'com.liquidexam.liquidExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ8t6TxhWYmJYWTwfYCwLqvX9ZuWxe4CU',
    appId: '1:699043853640:web:d22d0050c72c5a99ce6f7d',
    messagingSenderId: '699043853640',
    projectId: 'flarus-app',
    authDomain: 'flarus-app.firebaseapp.com',
    storageBucket: 'flarus-app.firebasestorage.app',
    measurementId: 'G-2ZMHE8QD32',
  );
}
